### PR TITLE
Adds a MSDynamicsDrawerShadowStyler

### PR DESCRIPTION
**Pull request by khoogheem**
Adds Shadow Styling to the PaneView

### CODE REVIEW

**Comment by stevekohls** [comment]
+1 I am planning on using this shadow styler in my upcoming app. Thanks!

**Comment by andepopande** [comment]
+1 :)

**Comment by khoogheem** [comment]
Thanks.. I am sure there is probably a more clean way to do it.. but really wanted to make sure that if you had both a left and right drawer you could have independent shadows..

**Comment by stevekohls** [comment]
Currently I'm only using one drawer, and even if I switch to using left and right, the shadow will be the same. Will let you know if I come up with any improvements.

**Comment by erichoracek** [comment]
I really like the idea of a shadow styler. I'm working now on integrating this and making some small changes to the implementation. Should have it done soon. Thanks @khoogheem!

One thing I'm not entirely sure about is the additional methods that were added to the interface of `MSDynamicsDrawerStyler`. What's the intended use case for them?

**Comment by erichoracek** [comment]
Added in #62.

**Comment by khoogheem** [comment]
The extra methods.. of change state where due to the fact that you don't know the Pane is open or shut until after the fact.. These were done to be warned that it is going to close or open.

I would have added that to the pull but forgot to add it as a new branch.. 
Here is my use case:
I have Banners loaded.. I want to tell the BannerManager to hide the Banner when the user intends to open the drawer and to Show when it is a close state.

**Pull request closed without merging**
