### PR TITLE
Add separate setting for dragging to close vs. dragging to reveal

### PR DESCRIPTION
**Pull request by MigrantP**
We're using the menu in an app that has horizontal paging, so we do not want to allow dragging to reveal the menu. However, we want to be able to drag to close the menu. I added a separate setting to enable this behaviour.

### CODE REVIEW

**Comment by fcanas** [comment]
You don't need a separate setting for this. You can disable panning to close on a class that you want to handle touch events. This is how it's possible for the demo app to have sliders that work without having the sliders close the drawer. Say you had a map view in the center panel, and you wanted to have panning work normally on the map view:

`[self.drawerViewController registerTouchForwardingClass:[MKMapView class]];`

Just register you paging view as a touch forwarding class.

**Comment by MigrantP** [comment]
That works for the map view, but not for the navigation bar. (I think!)

**Comment by fcanas** [comment]
Do you have a navigation bar that actually handles touches? Or do you have a title view that should handle touches. Have you tried registering each class as a touch forwarding class? I'm interested in seeing a specific scenario where registering a touch forwarding class doesn't work. Can you share code?

**Comment by erichoracek** [comment]
You can accomplish the behavior you want without adding an additional method to the dynamics drawer. Just use the delegate method:

``` objective-c
- (void)dynamicsDrawerViewController:(MSDynamicsDrawerViewController *)drawerViewController mayUpdateToPaneState:(MSDynamicsDrawerPaneState)paneState forDirection:(MSDynamicsDrawerDirection)direction
{
    [drawerViewController setPaneDragRevealEnabled:(paneState == MSDynamicsDrawerPaneStateOpen) forDirection:MSDynamicsDrawerDirectionAll];
}
```

And then at the initialization of your dynamics drawer set the following:

``` objective-c
[dynamicsDrawerViewController setPaneDragRevealEnabled:NO forDirection:MSDynamicsDrawerDirectionAll];
```

With these you will _only_ be able to use pan gestures to close the pane, rather than open them.

**Pull request closed without merging**
