### PR TITLE
Fix for the twitching behaviour described by issue #128.

### PR DESCRIPTION
**Pull request by bhapca**
Fixes a twitching behaviour that sometimes occurs when opening/closing the pane (see issue #128).

### CODE REVIEW

**Comment by brentd** [comment]
Just tried this and it works great for a left-side drawer, but unfortunately not a right-side (I have both).

**Comment by bhapca** [comment]
@brentd Indeed, the fix was only for the left-side drawer (that's what I was using when I needed this component in an app). Thanks for the notice ! 

I just added 2 more commits that fixes it for the remaining directions.

**Comment by yeraydiazdiaz** [comment]
thanks for this, you may want to add `MSDynamicsDrawerPaneStateOpenWide` to the conditions on `removeSlidingPaneJiggleEffect`, which fixes an additional pop that happens when `paneViewSlideOffAnimationEnabled` is set to `YES` and changing panes.

**Comment by bhapca** [comment]
This fix stopped working when building with iOS 9 as base SDK. I made an update on the branch https://github.com/bhapca/MSDynamicsDrawerViewController/tree/fix_twitch_iOS9 that seems to be working with iOS 9, but this whole approach seems too hackish and not future-proof. 

I'll close the PR and discontinue the support for this.

**Pull request closed without merging**
